# Generated by Django 6.0 on 2025-12-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="credential_id",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="credential_public_key",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="credential_signature",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="credential_user_handle",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
