# Generated by Django 6.0 on 2025-12-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_credential_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="sign_count",
            field=models.BigIntegerField(default=0),
        ),
    ]
