# Generated by Django 6.0 on 2025-12-27 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_activesession"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activesession",
            options={},
        ),
        migrations.AlterField(
            model_name="activesession",
            name="ip_address",
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name="activesession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="activesession",
            name="user_agent",
            field=models.TextField(null=True),
        ),
    ]
