# Generated by Django 6.0 on 2025-12-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_activesession_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activesession",
            name="access_jti",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
