# Generated by Django 6.0 on 2025-12-27 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_activesession_access_jti"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activesession",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="activesession",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activesession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="activesession",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="activesession",
            index=models.Index(
                fields=["user", "jti"], name="accounts_ac_user_id_008a2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activesession",
            index=models.Index(
                fields=["user", "access_jti"], name="accounts_ac_user_id_5d2a49_idx"
            ),
        ),
    ]
