# Generated by Django 6.0 on 2025-12-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_activesession_previous_access_jti"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="activesession",
            name="accounts_ac_user_id_5d2a49_idx",
        ),
        migrations.RemoveField(
            model_name="activesession",
            name="access_jti",
        ),
        migrations.RemoveField(
            model_name="activesession",
            name="previous_access_jti",
        ),
    ]
