# Generated by Django 6.0 on 2025-12-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0009_remove_activesession_accounts_ac_user_id_5d2a49_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="activesession",
            name="last_active",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
