# Generated by Django 5.2.9 on 2026-01-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_activesession_last_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="preferred_session_lifetime_days",
            field=models.PositiveIntegerField(
                choices=[
                    (7, "1 week"),
                    (14, "2 weeks"),
                    (30, "1 month"),
                    (60, "2 months"),
                    (90, "3 months"),
                    (180, "6 months"),
                ],
                default=7,
            ),
        ),
    ]
