# Generated by Django 5.2.8 on 2025-11-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0002_add_is_deleted_edit_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messagerecipient",
            options={"ordering": ["-created_date"]},
        ),
    ]
