# Generated by Django 5.2.8 on 2025-11-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0005_alter_messagerecipient_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messagerecipient",
            options={},
        ),
    ]
