# Generated by Django 5.2.8 on 2025-11-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0007_alter_messagerecipient_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messagerecipient",
            options={"ordering": ["pk"]},
        ),
    ]
