# Generated by Django 5.2.8 on 2025-11-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0011_remove_customuser_image_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="website",
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
