# Generated by Django 5.2.8 on 2025-11-19 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0014_message_reply_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagereaction",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_reactions",
                to="Site.message",
            ),
        ),
        migrations.AlterField(
            model_name="messagereaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
