# Generated by Django 5.2.8 on 2025-11-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0017_alter_file_options_file_file_size_file_file_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="thumbnail",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="profiles/thumbnails/"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="profiles/"
            ),
        ),
    ]
