# Generated by Django 5.2.8 on 2025-11-27 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0021_file_thumbnail_medium_file_thumbnail_small"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="thumbnail_small",
        ),
        migrations.RemoveField(
            model_name="file",
            name="thumbnail_medium",
        ),
        migrations.CreateModel(
            name="VideoFile",
            fields=[
                (
                    "file_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Site.file",
                    ),
                ),
            ],
            bases=("Site.file",),
        ),
        migrations.CreateModel(
            name="ImageFile",
            fields=[
                (
                    "file_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Site.file",
                    ),
                ),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "thumbnail_small",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="thumbnails/small/",
                    ),
                ),
                (
                    "thumbnail_medium",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="thumbnails/medium/",
                    ),
                ),
            ],
            bases=("Site.file",),
        ),
    ]
