# Generated by Django 5.2.8 on 2025-11-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0024_videofile_height_videofile_width"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagefile",
            name="dominant_color",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
