# Generated by Django 5.2.8 on 2025-12-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0026_remove_profile_image_remove_profile_thumbnail_medium_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
