# Generated by Django 5.2.8 on 2025-12-19 02:20

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0027_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profilephoto",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "фото профиля",
                "verbose_name_plural": "фото профилей",
            },
        ),
        migrations.RemoveField(
            model_name="profilephoto",
            name="medium",
        ),
        migrations.RemoveField(
            model_name="profilephoto",
            name="small",
        ),
        migrations.AddField(
            model_name="profilephoto",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="основное"),
        ),
        migrations.AddField(
            model_name="profilephoto",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="обновлено"),
        ),
        migrations.AlterField(
            model_name="profilephoto",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="создано"),
        ),
        migrations.AlterField(
            model_name="profilephoto",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                upload_to="profiles/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="profilephoto",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="активно"),
        ),
        migrations.AlterField(
            model_name="profilephoto",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="Site.profile",
                verbose_name="профиль",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilephoto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("profile", "is_primary"),
                name="unique_primary_photo_per_profile",
            ),
        ),
    ]
