# Generated by Django 5.2.8 on 2025-12-19 02:21

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0028_alter_profilephoto_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilephoto",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to="profiles/%Y/%m/%d/"
            ),
        ),
    ]
