# Generated by Django 5.2.8 on 2025-12-19 02:21

import django.utils.timezone
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0029_alter_profilephoto_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilephoto",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                default=django.utils.timezone.now, upload_to="profiles/%Y/%m/%d/"
            ),
            preserve_default=False,
        ),
    ]
