# Generated by Django 5.2.8 on 2025-12-19 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0030_alter_profilephoto_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profilephoto",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="profilephoto",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="profilephoto",
            name="image",
            field=models.ImageField(upload_to="profiles/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="profilephoto",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profilephoto",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profilephoto",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="Site.profile",
            ),
        ),
        migrations.AlterField(
            model_name="profilephoto",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
