# Generated by Django 5.2.8 on 2025-12-19 15:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0031_alter_profilephoto_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "video",
                    models.FileField(
                        upload_to="profiles/videos/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp4", "mov", "webm"]
                            )
                        ],
                    ),
                ),
                ("duration", models.FloatField(editable=False)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="profilephoto",
            name="unique_primary_photo_per_profile",
        ),
        migrations.AlterField(
            model_name="profilephoto",
            name="image",
            field=models.ImageField(
                upload_to="profiles/photos/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "gif"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profilephoto",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="profilephoto",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="Site.profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilephoto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("profile",),
                name="unique_primary_photo_per_profile",
            ),
        ),
        migrations.AddField(
            model_name="profilevideo",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="Site.profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilevideo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("profile",),
                name="unique_primary_video_per_profile",
            ),
        ),
    ]
