# Generated by Django 5.2.8 on 2025-12-19 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0032_profilevideo_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="profilevideo",
            name="unique_primary_video_per_profile",
        ),
    ]
