# Generated by Django 5.2.8 on 2025-12-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0033_remove_profilevideo_unique_primary_video_per_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilevideo",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
