# Generated by Django 5.2.8 on 2025-12-20 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0034_profilevideo_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilevideo",
            name="compressed_file",
            field=models.FileField(
                blank=True, null=True, upload_to="profiles/videos/compressed/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="profilevideo",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profilevideo",
            name="video",
            field=models.FileField(
                upload_to="profiles/videos/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["mp4", "mov", "webm"]
                    )
                ],
            ),
        ),
    ]
