# Generated by Django 5.2.8 on 2025-12-20 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0035_profilevideo_compressed_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilevideo",
            name="compressed_file",
        ),
    ]
