# Generated by Django 5.2.8 on 2025-12-21 00:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0036_remove_profilevideo_compressed_file"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRoomProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_name", models.CharField(blank=True, max_length=64, null=True)),
                ("is_blocked", models.BooleanField(default=False)),
                ("is_favorite", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="rooms",
        ),
        migrations.RemoveField(
            model_name="room",
            name="image",
        ),
        migrations.AddField(
            model_name="room",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[("D", "Dialog"), ("G", "Group"), ("C", "Channel")],
                default="D",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="users",
            field=models.ManyToManyField(
                related_name="rooms", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["username"], name="Site_custom_usernam_6f4a03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["room_type"], name="Site_room_room_ty_8d43c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["-created_at", "room_type"], name="Site_room_created_f53243_idx"
            ),
        ),
        migrations.AddField(
            model_name="userroomprofile",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profiles",
                to="Site.room",
            ),
        ),
        migrations.AddField(
            model_name="userroomprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userroomprofile",
            index=models.Index(
                fields=["user", "is_favorite"], name="Site_userro_user_id_eae483_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userroomprofile",
            index=models.Index(
                fields=["room", "is_blocked"], name="Site_userro_room_id_6e4697_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userroomprofile",
            unique_together={("user", "room")},
        ),
    ]
