# Generated by Django 6.0 on 2025-12-23 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Site", "0001_initial"),
        ("media_files", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="display_media",
            field=models.ManyToManyField(
                blank=True, related_name="chats", to="media_files.displaymedia"
            ),
        ),
        migrations.AddField(
            model_name="chatmember",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Site.chat"
            ),
        ),
        migrations.AddField(
            model_name="chatmember",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="chats",
                through="Site.ChatMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="Site.chat",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.ManyToManyField(
                blank=True, related_name="messages", to="media_files.file"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="forwarded",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="forwarded_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="Site.message",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="messagereaction",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_reactions",
                to="Site.message",
            ),
        ),
        migrations.AddField(
            model_name="messagereaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="messagerecipient",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipients",
                to="Site.message",
            ),
        ),
        migrations.AddField(
            model_name="messagerecipient",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_recipients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="viewed_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="viewed_messages",
                through="Site.MessageRecipient",
                through_fields=("message", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="chatmember",
            constraint=models.UniqueConstraint(
                fields=("chat", "user"), name="unique_chat_member"
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["-created_at", "chat_type"], name="Site_chat_created_7fb74b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                fields=("owner", "user"), name="unique_contact_per_owner"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagereaction",
            unique_together={("message", "user")},
        ),
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(
                fields=["user", "read_date", "is_deleted"],
                name="Site_messag_user_id_c58ee6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(
                fields=["message", "user"], name="Site_messag_message_142270_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagerecipient",
            unique_together={("message", "user")},
        ),
    ]
