# Generated by Django 6.0 on 2025-12-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="display_media",
        ),
    ]
