# Generated by Django 6.0 on 2025-12-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Site", "0003_remove_chat_display_media"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="custom_name",
            new_name="name",
        ),
    ]
